# permissions for end users to view relayrcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: relayrc-viewer-role
rules:
- apiGroups:
  - apps.relayrc.com
  resources:
  - relayrcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.relayrc.com
  resources:
  - relayrcs/status
  verbs:
  - get
