# permissions for end users to edit relayrcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: relayrc-editor-role
rules:
- apiGroups:
  - apps.relayrc.com
  resources:
  - relayrcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.relayrc.com
  resources:
  - relayrcs/status
  verbs:
  - get
